/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplo.jflex;

import compilador.ast.ContextoLLVM;
import compilador.ast.GestorStringsLLVM;
import compilador.ast.Programa;
import java.awt.Image;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Usuario
 */
public class AnalizadorGUI extends javax.swing.JFrame {

    /**
     * Creates new form AnalizadorGUI
     */
    public AnalizadorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAnalisisLexico = new javax.swing.JButton();
        botonAnalisisSintactico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEntrada = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonGenerarAST = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador GUI- Grupo 1");
        setName("AnalizadorGUI"); // NOI18N

        botonAnalisisLexico.setActionCommand("Análisis Léxico");
        botonAnalisisLexico.setLabel("Análisis Lexico");
        botonAnalisisLexico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnalisisLexicoMouseClicked(evt);
            }
        });
        botonAnalisisLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalisisLexicoActionPerformed(evt);
            }
        });

        botonAnalisisSintactico.setText("Análisis Sintáctico");
        botonAnalisisSintactico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnalisisSintacticoMouseClicked(evt);
            }
        });

        textAreaEntrada.setColumns(20);
        textAreaEntrada.setRows(5);
        textAreaEntrada.setText("Escriba el programa a analizar...");
        jScrollPane1.setViewportView(textAreaEntrada);

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        outputTextArea.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                outputTextAreaPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(outputTextArea);

        jLabel1.setText("Salida del analizador...");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Trabajo Compilador - Grupo 1- UNNOBA 2025 ");
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 20));

        botonGenerarAST.setText("Generar AST- LLVM");
        botonGenerarAST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGenerarASTMouseClicked(evt);
            }
        });
        botonGenerarAST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarASTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(botonAnalisisLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58)
                                            .addComponent(botonAnalisisSintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(60, 60, 60)
                                            .addComponent(botonGenerarAST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnalisisLexico)
                    .addComponent(botonAnalisisSintactico)
                    .addComponent(botonGenerarAST))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        botonGenerarAST.getAccessibleContext().setAccessibleName("Generar AST - LLVM");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnalisisLexicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnalisisLexicoMouseClicked
           new Thread(() -> {
        String inputText = textAreaEntrada.getText()+" ";
        MiLexico lexico = new MiLexico(new StringReader(inputText));
        System.out.println("...............................");
        System.out.println("Análisis léxico iniciado...");
        try {
            Symbol token;
            while ((token = lexico.next_token()) != null) {
                if (token.toString().equals("#0")) break; // Si detecta Token 0, termina
                System.out.println("Token: " + token.toString());
        }

        } catch (IOException ex) {
            Logger.getLogger(AnalizadorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("...............................");
         }).start();


    }//GEN-LAST:event_botonAnalisisLexicoMouseClicked

    private void outputTextAreaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_outputTextAreaPropertyChange
            PrintStream printStream = new PrintStream(new TextAreaOutputStream(outputTextArea));
            System.setOut(printStream);
            System.setErr(printStream);

    }//GEN-LAST:event_outputTextAreaPropertyChange

    private void botonAnalisisSintacticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnalisisSintacticoMouseClicked
       new Thread(() -> {
        String inputText = textAreaEntrada.getText()+" ";
        MiLexico lexico = new MiLexico(new StringReader(inputText));
        System.out.println("...............................");
        System.out.println("Análisis Sintáctico iniciado...");
        try {
            MiParser parser = new MiParser(lexico);
            Symbol resultado = parser.parse();
        
        } catch (IOException ex) {
            Logger.getLogger(AnalizadorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }  catch (Exception ex) {
               Logger.getLogger(AnalizadorGUI.class.getName()).log(Level.SEVERE, null, ex);
               System.out.println(ex);
           }
        System.out.println("...............................");

         }).start();
          
       
    }//GEN-LAST:event_botonAnalisisSintacticoMouseClicked

    private void botonAnalisisLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalisisLexicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAnalisisLexicoActionPerformed

    private void botonGenerarASTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGenerarASTMouseClicked
        // TODO add your handling code here:
        new Thread(() -> {
        String inputText = textAreaEntrada.getText()+" ";
        MiLexico lexico = new MiLexico(new StringReader(inputText));
        System.out.println("...............................");
        System.out.println("Análisis Sintáctico iniciado...");
        try {     
            MiParser parser = new MiParser(lexico);
            Symbol resultado = parser.parse();
            Programa programa = (Programa) resultado.value;
            String dot = programa.graficar();
             //String dot = programa.graficar();
            //System.out.println(dot);
            PrintWriter grafico = new PrintWriter(new FileWriter("arbol.dot"));
            grafico.println(programa.graficar());
            grafico.close();
            System.out.println("Archivo arbol.dot creado.");
            System.out.println(new File("arbol.dot").getAbsolutePath());
            String cmdDot = "dot -Tpng arbol.dot -o arbol.png";
            Process process = Runtime.getRuntime().exec(cmdDot);
            process.waitFor(); // Esperar que Graphviz termine de generar la imagen
            System.out.println("Archivo arbol.png creado.");
            System.out.println(new File("arbol.png").getAbsolutePath());
            ContextoLLVM ctx = new ContextoLLVM();               
            String codigoLLVM = programa.generarCodigoLLVM(ctx);                
            Files.write(Paths.get("programa.ll"), codigoLLVM.getBytes());
            System.out.println("Archivo programa.ll creado.");
            System.out.println(new File("programa.ll").getAbsolutePath());
            GestorStringsLLVM.reset();
        
        } catch (IOException ex) {
            Logger.getLogger(AnalizadorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }  catch (Exception ex) {
               Logger.getLogger(AnalizadorGUI.class.getName()).log(Level.SEVERE, null, ex);
               System.out.println(ex);
           }
        System.out.println("...............................");


         }).start();
        
    }//GEN-LAST:event_botonGenerarASTMouseClicked

    private void botonGenerarASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarASTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGenerarASTActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizadorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizadorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizadorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizadorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalizadorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnalisisLexico;
    private javax.swing.JButton botonAnalisisSintactico;
    private javax.swing.JButton botonGenerarAST;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JTextArea textAreaEntrada;
    // End of variables declaration//GEN-END:variables
}
