
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ejemplo.jflex;

/** CUP generated class containing symbol constants. */
public class MiParserSym {
  /* terminals */
  public static final int PROMEDIO_PONDERADO = 54;
  public static final int DISPLAY = 45;
  public static final int ENDDECLARE_SECTION = 3;
  public static final int TYPE_BOOLEAN = 9;
  public static final int LIT_BOOLEAN = 15;
  public static final int LOOP_WHEN = 27;
  public static final int ANY = 53;
  public static final int BACKWARD_LOOP_WHEN = 28;
  public static final int CORCHETE_CERRADO = 12;
  public static final int END_LOOP = 29;
  public static final int LIT_FLOAT = 14;
  public static final int OP_AND = 43;
  public static final int OP_NOT = 42;
  public static final int CONTINUE = 31;
  public static final int INPUT_ARRAY = 49;
  public static final int OP_DIV = 35;
  public static final int IDENTIFICADOR = 18;
  public static final int PAREN_CERRADO = 51;
  public static final int OP_ME = 39;
  public static final int OP_MA = 38;
  public static final int OP_MUL = 34;
  public static final int ELSE_BACKWARD = 25;
  public static final int CONDITION = 21;
  public static final int BACKWARD_CONDITION = 22;
  public static final int OP_NEQ = 37;
  public static final int CORCHETE_ABIERTO = 11;
  public static final int EOF = 0;
  public static final int INPUT_INT = 46;
  public static final int error = 1;
  public static final int COMA = 19;
  public static final int LIT_STRING = 16;
  public static final int INPUT_BOOL = 48;
  public static final int LIT_ARRAY = 17;
  public static final int OP_OR = 44;
  public static final int TYPE_FLOAT_ARRAY = 10;
  public static final int BREAK = 30;
  public static final int TYPE_FLOAT = 8;
  public static final int ASIGNACION = 20;
  public static final int DECLARACION = 6;
  public static final int OP_MEI = 41;
  public static final int ELSE = 24;
  public static final int OP_IGUAL = 36;
  public static final int OP_SUM = 32;
  public static final int PAREN_ABIERTO = 50;
  public static final int TYPE_INTEGER = 7;
  public static final int LIT_INTEGER = 13;
  public static final int THEN = 23;
  public static final int PROGRAM_SECTION = 4;
  public static final int OP_SUB = 33;
  public static final int END = 26;
  public static final int INPUT_FLOAT = 47;
  public static final int ALL = 52;
  public static final int ENDPROGRAM_SECTION = 5;
  public static final int OP_MAI = 40;
  public static final int DECLARE_SECTION = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECLARE_SECTION",
  "ENDDECLARE_SECTION",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION",
  "DECLARACION",
  "TYPE_INTEGER",
  "TYPE_FLOAT",
  "TYPE_BOOLEAN",
  "TYPE_FLOAT_ARRAY",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "LIT_INTEGER",
  "LIT_FLOAT",
  "LIT_BOOLEAN",
  "LIT_STRING",
  "LIT_ARRAY",
  "IDENTIFICADOR",
  "COMA",
  "ASIGNACION",
  "CONDITION",
  "BACKWARD_CONDITION",
  "THEN",
  "ELSE",
  "ELSE_BACKWARD",
  "END",
  "LOOP_WHEN",
  "BACKWARD_LOOP_WHEN",
  "END_LOOP",
  "BREAK",
  "CONTINUE",
  "OP_SUM",
  "OP_SUB",
  "OP_MUL",
  "OP_DIV",
  "OP_IGUAL",
  "OP_NEQ",
  "OP_MA",
  "OP_ME",
  "OP_MAI",
  "OP_MEI",
  "OP_NOT",
  "OP_AND",
  "OP_OR",
  "DISPLAY",
  "INPUT_INT",
  "INPUT_FLOAT",
  "INPUT_BOOL",
  "INPUT_ARRAY",
  "PAREN_ABIERTO",
  "PAREN_CERRADO",
  "ALL",
  "ANY",
  "PROMEDIO_PONDERADO"
  };
}

